# Generated by Django 2.2.1 on 2019-05-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velvet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.CharField(max_length=50)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='velvet.Blog')),
            ],
        ),
    ]
